services:
  - type: web
    name: outertiers
    env: static
    buildCommand: npm install -g pnpm && pnpm install --config.approve-builds=true && pnpm exec vite build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
